name=MiLcd
version=1.0.0
author=Juan-Arjona
sentence=Libreria LCD en modo 4 bits
paragraph=Controla pantallas LCD HD44780 en modo 4 bits
category=Display
url=https://github.com/iarjonaollero-web/MiLcd
architectures=avr
